build:
	export PATH=$PATH:$GOPATH/bin
	protoc -I/usr/local/include -I. -I$(GOPATH)/src -I$(GOPATH)/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis --go_out=plugins=grpc:. proto/consignment/consignment.proto
	go get -u -f github.com/Kavit900/message-scheduler/consignment-service